// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC187N1vP6-vGwLhGAdF883MBNo4rR66ic',
    appId: '1:945178037316:web:ce3361d3eebf1207dbc011',
    messagingSenderId: '945178037316',
    projectId: 'blooddonationapp-cf4d3',
    authDomain: 'blooddonationapp-cf4d3.firebaseapp.com',
    storageBucket: 'blooddonationapp-cf4d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQWMMAuisdDaqWx5qSTou2f1UNK8YqkIc',
    appId: '1:945178037316:android:e2ef5dcbb4ff482fdbc011',
    messagingSenderId: '945178037316',
    projectId: 'blooddonationapp-cf4d3',
    storageBucket: 'blooddonationapp-cf4d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKtqvLPylf2HTSLnfE9lDUMG0bGMhfwFs',
    appId: '1:945178037316:ios:deaeed33235c83c4dbc011',
    messagingSenderId: '945178037316',
    projectId: 'blooddonationapp-cf4d3',
    storageBucket: 'blooddonationapp-cf4d3.appspot.com',
    iosBundleId: 'com.example.blooddonation',
  );
}